import { AccountCategory } from './Account';

export interface TransactionLine {
  accountCategory: AccountCategory;
  debit: number;
  credit: number;
  description?: string;
}

export interface JournalEntry {
  id: string;
  date: GameDate;
  description: string;
  descriptionJa: string;
  lines: TransactionLine[];
  eventType: BusinessEventType;
  chapter: number;
  validated: boolean;
}

export interface GameDate {
  year: number;
  month: number;
  day: number;
}

export enum BusinessEventType {
  // Chapter 1: Basic Transactions
  OWNER_INVESTMENT = 'OWNER_INVESTMENT',
  CASH_PURCHASE = 'CASH_PURCHASE',
  CASH_SALE = 'CASH_SALE',

  // Chapter 2: Profit Calculation
  RECORD_EXPENSE = 'RECORD_EXPENSE',
  PAY_WAGES = 'PAY_WAGES',

  // Chapter 3: Borrowing & Credit
  TAKE_LOAN = 'TAKE_LOAN',
  REPAY_LOAN = 'REPAY_LOAN',
  CREDIT_PURCHASE = 'CREDIT_PURCHASE',
  PAY_ACCOUNTS_PAYABLE = 'PAY_ACCOUNTS_PAYABLE',

  // Chapter 4: Advanced Revenue
  CREDIT_SALE = 'CREDIT_SALE',
  COLLECT_RECEIVABLE = 'COLLECT_RECEIVABLE',
  WRITE_OFF_BAD_DEBT = 'WRITE_OFF_BAD_DEBT',

  // Chapter 5: Service Business
  SERVICE_REVENUE = 'SERVICE_REVENUE',
  RECEIVE_ADVANCE = 'RECEIVE_ADVANCE',
  EARN_UNEARNED_REVENUE = 'EARN_UNEARNED_REVENUE',

  // Chapter 6: Inventory
  PURCHASE_INVENTORY = 'PURCHASE_INVENTORY',
  SELL_INVENTORY = 'SELL_INVENTORY',

  // Chapter 7: Fixed Assets
  PURCHASE_EQUIPMENT = 'PURCHASE_EQUIPMENT',
  RECORD_DEPRECIATION = 'RECORD_DEPRECIATION',

  // Chapter 8: Cash Flow
  OPERATING_ACTIVITY = 'OPERATING_ACTIVITY',
  INVESTING_ACTIVITY = 'INVESTING_ACTIVITY',
  FINANCING_ACTIVITY = 'FINANCING_ACTIVITY',

  // Chapter 9: Taxes
  RECORD_TAX_EXPENSE = 'RECORD_TAX_EXPENSE',
  PAY_TAX = 'PAY_TAX',

  // Chapter 10: Analysis
  CLOSING_ENTRY = 'CLOSING_ENTRY',
  DIVIDEND = 'DIVIDEND',

  // ========== Lv2 Events ==========

  // Lv2 Chapter 1: Incorporation
  INCORPORATE_COMPANY = 'INCORPORATE_COMPANY',
  OPEN_BANK_ACCOUNT = 'OPEN_BANK_ACCOUNT',
  PAY_SECURITY_DEPOSIT = 'PAY_SECURITY_DEPOSIT',

  // Lv2 Chapter 2: Store Opening
  PURCHASE_BUILDING = 'PURCHASE_BUILDING',
  PURCHASE_VEHICLE = 'PURCHASE_VEHICLE',
  PAY_ADVANCE = 'PAY_ADVANCE',
  RECORD_ACCOUNTS_PAYABLE_OTHER = 'RECORD_ACCOUNTS_PAYABLE_OTHER',
  PAY_ADVERTISING = 'PAY_ADVERTISING',

  // Lv2 Chapter 3: Purchasing
  ELECTRONIC_RECEIVABLE = 'ELECTRONIC_RECEIVABLE',
  ELECTRONIC_PAYABLE = 'ELECTRONIC_PAYABLE',
  PAY_SHIPPING = 'PAY_SHIPPING',
  PAY_COMMUNICATION = 'PAY_COMMUNICATION',
  PAY_UTILITIES_LV2 = 'PAY_UTILITIES_LV2',

  // Lv2 Chapter 4: Consumption Tax
  RECORD_CONSUMPTION_TAX_RECEIVABLE = 'RECORD_CONSUMPTION_TAX_RECEIVABLE',
  RECORD_CONSUMPTION_TAX_PAYABLE = 'RECORD_CONSUMPTION_TAX_PAYABLE',
  SETTLE_CONSUMPTION_TAX = 'SETTLE_CONSUMPTION_TAX',
  PAY_TAXES_AND_DUES = 'PAY_TAXES_AND_DUES',

  // Lv2 Chapter 5: Hiring
  PAY_WAGES_WITH_WITHHOLDING = 'PAY_WAGES_WITH_WITHHOLDING',
  PAY_STATUTORY_WELFARE = 'PAY_STATUTORY_WELFARE',
  PAY_ADVANCES_FOR_EMPLOYEE = 'PAY_ADVANCES_FOR_EMPLOYEE',

  // Lv2 Chapter 6: Cash Management
  PETTY_CASH_FUND = 'PETTY_CASH_FUND',
  PETTY_CASH_REPLENISH = 'PETTY_CASH_REPLENISH',
  RECORD_CASH_SHORTAGE = 'RECORD_CASH_SHORTAGE',
  OVERDRAFT_BORROWING = 'OVERDRAFT_BORROWING',
  RECORD_TEMPORARY_PAYMENT = 'RECORD_TEMPORARY_PAYMENT',
  RECORD_TEMPORARY_RECEIPT = 'RECORD_TEMPORARY_RECEIPT',

  // Lv2 Chapter 7: Diverse Sales
  CREDIT_CARD_SALE = 'CREDIT_CARD_SALE',
  GIFT_CERTIFICATE_SALE = 'GIFT_CERTIFICATE_SALE',
  RECORD_COMMISSION_INCOME = 'RECORD_COMMISSION_INCOME',
  PAY_COMMISSION_EXPENSE = 'PAY_COMMISSION_EXPENSE',

  // Lv2 Chapter 8: Allowance for Doubtful Accounts
  RECORD_ALLOWANCE_FOR_DA = 'RECORD_ALLOWANCE_FOR_DA',
  RECORD_BAD_DEBT_WITH_ALLOWANCE = 'RECORD_BAD_DEBT_WITH_ALLOWANCE',

  // Lv2 Chapter 9: Accruals
  RECORD_ACCRUED_EXPENSE = 'RECORD_ACCRUED_EXPENSE',
  RECORD_ACCRUED_REVENUE = 'RECORD_ACCRUED_REVENUE',
  REVERSE_ENTRY = 'REVERSE_ENTRY',

  // Lv2 Chapter 10: Fixed Asset Disposal
  SELL_FIXED_ASSET_GAIN = 'SELL_FIXED_ASSET_GAIN',
  SELL_FIXED_ASSET_LOSS = 'SELL_FIXED_ASSET_LOSS',
  PAY_INSURANCE = 'PAY_INSURANCE',
  RECORD_SUPPLIES_INVENTORY = 'RECORD_SUPPLIES_INVENTORY',
  PAY_REPAIR = 'PAY_REPAIR',

  // Lv2 Chapter 11: Closing Adjustments
  CLOSING_ADJUSTMENT_INVENTORY = 'CLOSING_ADJUSTMENT_INVENTORY',
  CLOSING_ADJUSTMENT_DEPRECIATION_MONTHLY = 'CLOSING_ADJUSTMENT_DEPRECIATION_MONTHLY',
  RECORD_CORPORATE_TAX = 'RECORD_CORPORATE_TAX',

  // Lv2 Chapter 12: Monthly Closing
  PREPARE_TRIAL_BALANCE = 'PREPARE_TRIAL_BALANCE',
  RECORD_LEGAL_RESERVE = 'RECORD_LEGAL_RESERVE',

  // ========== Lv3 Events ==========

  // Lv3 Chapter 1: Factory
  PURCHASE_RAW_MATERIALS = 'PURCHASE_RAW_MATERIALS',
  ISSUE_MATERIALS_TO_PRODUCTION = 'ISSUE_MATERIALS_TO_PRODUCTION',
  RECORD_DIRECT_LABOR = 'RECORD_DIRECT_LABOR',
  RECORD_MANUFACTURING_OVERHEAD = 'RECORD_MANUFACTURING_OVERHEAD',
  COMPLETE_PRODUCTION = 'COMPLETE_PRODUCTION',

  // Lv3 Chapter 2: Cost Accounting
  ALLOCATE_OVERHEAD = 'ALLOCATE_OVERHEAD',
  TRANSFER_TO_FINISHED_GOODS = 'TRANSFER_TO_FINISHED_GOODS',

  // Lv3 Chapter 3: Standard Costing
  RECORD_STANDARD_COST = 'RECORD_STANDARD_COST',
  RECORD_VARIANCE = 'RECORD_VARIANCE',

  // Lv3 Chapter 4: CVP Analysis
  CVP_ANALYSIS_ENTRY = 'CVP_ANALYSIS_ENTRY',

  // Lv3 Chapter 5: Securities
  PURCHASE_TRADING_SECURITIES = 'PURCHASE_TRADING_SECURITIES',
  SELL_TRADING_SECURITIES = 'SELL_TRADING_SECURITIES',
  REVALUE_SECURITIES = 'REVALUE_SECURITIES',
  PURCHASE_HTM_SECURITIES = 'PURCHASE_HTM_SECURITIES',

  // Lv3 Chapter 6: Subsidiary
  ACQUIRE_SUBSIDIARY = 'ACQUIRE_SUBSIDIARY',
  RECORD_GOODWILL = 'RECORD_GOODWILL',
  AMORTIZE_GOODWILL = 'AMORTIZE_GOODWILL',

  // Lv3 Chapter 7: Consolidation
  ELIMINATE_INTERCOMPANY = 'ELIMINATE_INTERCOMPANY',
  CONSOLIDATION_ADJUSTMENT = 'CONSOLIDATION_ADJUSTMENT',

  // Lv3 Chapter 8: Shareholders
  DECLARE_DIVIDEND = 'DECLARE_DIVIDEND',
  PAY_DIVIDEND = 'PAY_DIVIDEND',
  TRANSFER_TO_LEGAL_RESERVE = 'TRANSFER_TO_LEGAL_RESERVE',
  TRANSFER_TO_CAPITAL_SURPLUS = 'TRANSFER_TO_CAPITAL_SURPLUS',

  // Lv3 Chapter 9: Cash Flow
  CASH_FLOW_ADJUSTMENT = 'CASH_FLOW_ADJUSTMENT',

  // Lv3 Chapter 10: Analysis
  COMPREHENSIVE_ANALYSIS = 'COMPREHENSIVE_ANALYSIS',
}

export function createJournalEntry(
  id: string,
  date: GameDate,
  description: string,
  descriptionJa: string,
  lines: TransactionLine[],
  eventType: BusinessEventType,
  chapter: number
): JournalEntry {
  return {
    id,
    date,
    description,
    descriptionJa,
    lines,
    eventType,
    chapter,
    validated: false,
  };
}

export function formatGameDate(date: GameDate): string {
  return `Year ${date.year}, Month ${date.month}, Day ${date.day}`;
}

export function formatGameDateJa(date: GameDate): string {
  return `${date.year}年${date.month}月${date.day}日`;
}
